apiVersion: v1
kind: Pod
metadata:
  name: deall-rest-api
spec:
  containers:
    - name: deall-rest-api
      image: deall-rest-api:0.0.1
      ports:
        - containerPort: 3000
    - name: mongo
      image: mongo:latest
      ports:
        - containerPort: 27017
